[package]
name = "fluent-template-helper"
version = "0.4.2"
authors = ["XAMPPRocky <xampprocky@icloud.com>"]
edition = "2018"
description = "Template helpers for the Fluent internationalization framework"
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/fluent-template-helper/"
repository = "https://github.com/XAMPPRocky/fluent-template-helper"
keywords = ["handlebars", "tera", "fluent", "internationalization", "localization"]
categories = ["internationalization", "localization", "template-engine"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
handlebars = "3"
lazy_static = "1.2.0"
fluent = "0.11"
fluent-bundle = "0.11"
fluent-syntax = "0.9.3"
fluent-langneg = "0.12.0"
serde_json = "1.0"
unic-langid = { version = "0.8.0", features = ["macros"] }

[dev-dependencies]
tempfile = "3.1.0"
